document.addEventListener("DOMContentLoaded",async()=>{
 const login=qs("adminLogin"),app=qs("adminApp");
 try{const me=await fetch("/api/me",{credentials:"same-origin"}).then(r=>r.json());if(me.authenticated){login.style.display="none";app.style.display="block";const csrf=await fetch("/api/csrf",{credentials:"same-origin"}).then(r=>r.json());window.__csrfToken=csrf.token;await initAdmin();}else{login.style.display="flex";app.style.display="none";}}catch(e){login.style.display="flex";app.style.display="none";}
 qs("loginForm").addEventListener("submit",async e=>{e.preventDefault();try{const r=await fetch("/api/login",{method:"POST",headers:{"Content-Type":"application/json"},credentials:"same-origin",body:JSON.stringify({username:qs("adminUser").value,password:qs("adminPass").value})});const j=await r.json();if(!r.ok)throw new Error(j.error);location.reload();}catch(err){qs("loginError").textContent=err.message;}});
 qs("logoutBtn").onclick=async()=>{await fetch("/api/logout",{method:"POST",headers:{"X-CSRF-Token":window.__csrfToken||""},credentials:"same-origin"});location.reload();};
});
function qs(id){return document.getElementById(id);}
async function initAdmin(){bindTabs();const data=await loadServerData();bindProfile(data);bindSkills(data);bindProjects(data);bindPortfolio(data);bindServices(data);bindBlog(data);bindDataTools();await renderMessages();updateStats(data);}
function bindTabs(){document.querySelectorAll(".admin-nav button[data-section]").forEach(b=>b.onclick=()=>{document.querySelectorAll(".admin-nav button").forEach(x=>x.classList.remove("active"));document.querySelectorAll(".admin-section").forEach(x=>x.classList.remove("active"));b.classList.add("active");qs(b.dataset.section).classList.add("active");});}
function updateStats(d){qs("statProjects").textContent=d.projects?.length||0;qs("statPortfolio").textContent=d.portfolio?.length||0;qs("statServices").textContent=d.services?.length||0;qs("statPosts").textContent=d.posts?.length||0;}
async function persist(d){const r=await saveServerData(d);if(r?.localOnly)alert("Server unavailable. A local browser copy was saved.");updateStats(d);}
function bindProfile(d){const f=qs("profileForm");["name","title","tagline","bio","email","phone","location","availability","linkedin","github","telegram"].forEach(k=>{const e=f.querySelector(`[name="${k}"]`);if(e)e.value=d.profile?.[k]||"";});f.onsubmit=async e=>{e.preventDefault();const n=getPortfolioData();new FormData(f).forEach((v,k)=>n.profile[k]=v);await persist(n);alert("Profile saved.");};}
function row(x){return `<div class="admin-row"><div><strong>${escapeHTML(x.name||x.title)}</strong><small>${escapeHTML(x.category||x.date||"")}</small></div><div><button class="btn small ghost" data-edit="${x.id}">Edit</button><button class="btn small danger" data-delete="${x.id}">Delete</button></div></div>`;}
function wireList(id,key,edit){const box=qs(id),d=getPortfolioData();box.innerHTML=(d[key]||[]).map(row).join("");box.querySelectorAll("[data-edit]").forEach(b=>b.onclick=()=>edit(b.dataset.edit));box.querySelectorAll("[data-delete]").forEach(b=>b.onclick=async()=>{if(!confirm("Delete this item?"))return;const n=getPortfolioData();const item=n[key].find(v=>v.id===b.dataset.delete);if(!item)return;try{const r=await fetch(`/api/${key}/${encodeURIComponent(item.id)}`,{method:"DELETE",headers:{"X-CSRF-Token":window.__csrfToken||""},credentials:"same-origin"});if(!r.ok)throw new Error();n[key]=n[key].filter(v=>v.id!==item.id);savePortfolioData(n);wireList(id,key,edit);updateStats(n);}catch(e){alert("Delete failed.");}});}
function bindSkills(){const f=qs("skillForm");f.onsubmit=async e=>{e.preventDefault();const d=getPortfolioData(),item={id:qs("skillId").value||portfolioId("s"),name:qs("skillName").value.trim(),category:qs("skillCategory").value.trim(),level:Number(qs("skillLevel").value)||0};await upsert("skills",item);f.reset();qs("skillId").value="";wireList("skillList","skills",editSkill);};qs("cancelSkill").onclick=()=>{f.reset();qs("skillId").value=""};wireList("skillList","skills",editSkill);}
function editSkill(id){const x=getPortfolioData().skills.find(v=>v.id===id);if(x){qs("skillId").value=x.id;qs("skillName").value=x.name;qs("skillCategory").value=x.category;qs("skillLevel").value=x.level;}}
function bindProjects(){const f=qs("projectForm");f.onsubmit=async e=>{e.preventDefault();const item={id:qs("projectId").value||portfolioId("p"),title:qs("projectTitle").value.trim(),category:qs("projectCategory").value.trim(),description:qs("projectDescription").value.trim(),tech:qs("projectTech").value.split(",").map(x=>x.trim()).filter(Boolean),demo:qs("projectDemo").value||"#",github:qs("projectGithub").value||"#",featured:qs("projectFeatured").checked,image:qs("projectImage")?.value||""};await upsert("projects",item);f.reset();qs("projectId").value="";wireList("projectList","projects",editProject);};qs("cancelProject").onclick=()=>{f.reset();qs("projectId").value=""};wireList("projectList","projects",editProject);}
function editProject(id){const x=getPortfolioData().projects.find(v=>v.id===id);if(x){["projectId","projectTitle","projectCategory","projectDescription","projectDemo","projectGithub"].forEach((id,i)=>{const key=["id","title","category","description","demo","github"][i];if(qs(id))qs(id).value=x[key]||""});qs("projectTech").value=(x.tech||[]).join(", ");qs("projectFeatured").checked=!!x.featured;if(qs("projectImage"))qs("projectImage").value=x.image||"";}}
function bindPortfolio(){const f=qs("portfolioForm");f.onsubmit=async e=>{e.preventDefault();const item={id:qs("portfolioId").value||portfolioId("pf"),title:qs("portfolioTitle").value.trim(),category:qs("portfolioCategory").value.trim(),description:qs("portfolioDescription").value.trim(),link:qs("portfolioLink").value||"#",image:qs("portfolioImage")?.value||""};await upsert("portfolio",item);f.reset();qs("portfolioId").value="";wireList("portfolioList","portfolio",editPortfolio);};qs("cancelPortfolio").onclick=()=>{f.reset();qs("portfolioId").value=""};wireList("portfolioList","portfolio",editPortfolio);}
function editPortfolio(id){const x=getPortfolioData().portfolio.find(v=>v.id===id);if(x){qs("portfolioId").value=x.id;qs("portfolioTitle").value=x.title;qs("portfolioCategory").value=x.category;qs("portfolioDescription").value=x.description;qs("portfolioLink").value=x.link||"";if(qs("portfolioImage"))qs("portfolioImage").value=x.image||"";}}
function bindServices(){const f=qs("serviceForm");f.onsubmit=async e=>{e.preventDefault();const item={id:qs("serviceId").value||portfolioId("sv"),title:qs("serviceTitle").value.trim(),icon:qs("serviceIcon").value||"✦",description:qs("serviceDescription").value.trim()};await upsert("services",item);f.reset();qs("serviceId").value="";wireList("serviceList","services",editService);};qs("cancelService").onclick=()=>{f.reset();qs("serviceId").value=""};wireList("serviceList","services",editService);}
function editService(id){const x=getPortfolioData().services.find(v=>v.id===id);if(x){qs("serviceId").value=x.id;qs("serviceTitle").value=x.title;qs("serviceIcon").value=x.icon;qs("serviceDescription").value=x.description;}}
function bindBlog(){const f=qs("blogForm");f.onsubmit=async e=>{e.preventDefault();const item={id:qs("blogId").value||portfolioId("b"),title:qs("blogTitle").value.trim(),date:qs("blogDate").value,category:qs("blogCategory").value.trim(),excerpt:qs("blogExcerpt").value.trim(),content:qs("blogContent").value.trim()};await upsert("posts",item);f.reset();qs("blogId").value="";wireList("blogList","posts",editBlog);};qs("cancelBlog").onclick=()=>{f.reset();qs("blogId").value=""};wireList("blogList","posts",editBlog);}
function editBlog(id){const x=getPortfolioData().posts.find(v=>v.id===id);if(x){qs("blogId").value=x.id;qs("blogTitle").value=x.title;qs("blogDate").value=x.date;qs("blogCategory").value=x.category;qs("blogExcerpt").value=x.excerpt;qs("blogContent").value=x.content;}}
async function upsert(key,item){
 try{
  const exists=(getPortfolioData()[key]||[]).some(x=>x.id===item.id);
  const r=await fetch(`/api/${key}${exists?"/"+encodeURIComponent(item.id):""}`,{method:exists?"PUT":"POST",headers:{"Content-Type":"application/json","X-CSRF-Token":window.__csrfToken||""},credentials:"same-origin",body:JSON.stringify(item)});
  const result=await r.json().catch(()=>({}));
  if(!r.ok) throw new Error(result.error||`Save failed (${r.status})`);
  const fresh=await loadServerData();
  updateStats(fresh);
 }catch(e){alert(e.message||"Save failed.");throw e;}
}
function bindDataTools(){
 const ub=qs("uploadBtn"); if(ub)ub.onclick=async()=>{const f=qs("imageUpload").files[0];if(!f)return alert("Choose an image.");const fd=new FormData();fd.append("file",f);ub.disabled=true;try{const r=await fetch("/api/upload",{method:"POST",headers:{"X-CSRF-Token":window.__csrfToken||""},body:fd,credentials:"same-origin"});const j=await r.json();if(!r.ok)throw new Error(j.error);qs("uploadResult").textContent="Uploaded: "+j.url;}catch(e){qs("uploadResult").textContent=e.message;}finally{ub.disabled=false;}};
 qs("resetData").onclick=async()=>{if(!confirm("Reset server portfolio content to the starter demo data? This replaces current saved content."))return;try{const result=await saveServerData(resetPortfolioData());if(result?.localOnly||result?.ok===false)throw new Error("Server reset failed. Your server data was not confirmed as updated.");alert("Server portfolio data reset to starter content.");location.reload();}catch(e){alert(e.message||"Reset failed.");}};qs("exportData").onclick=()=>{const blob=new Blob([JSON.stringify(getPortfolioData(),null,2)],{type:"application/json"}),a=document.createElement("a");a.href=URL.createObjectURL(blob);a.download="portfolio-data.json";a.click();};qs("importData").onchange=e=>{const f=e.target.files[0];if(!f)return;const r=new FileReader();r.onload=async()=>{try{const d=JSON.parse(r.result);const result=await saveServerData(d);if(result?.localOnly||result?.ok===false)throw new Error("Import could not be saved to the server.");alert("Portfolio data imported successfully.");location.reload();}catch(x){alert(x.message||"Invalid JSON.");}};r.readAsText(f);};}
async function renderMessages(){const box=qs("messageList");if(!box)return;try{const r=await fetch("/api/messages",{credentials:"same-origin"});const items=await r.json();box.innerHTML=items.length?items.slice().reverse().map(m=>`<div class="admin-row"><div><strong>${escapeHTML(m.name)} · ${escapeHTML(m.email)}</strong><small>${escapeHTML(m.createdAt)} · ${escapeHTML(m.subject)}</small><p>${escapeHTML(m.message)}</p></div></div>`).join(""):"<p class='note'>No messages yet.</p>";}catch(e){box.innerHTML="<p class='note'>Unable to load messages.</p>";}}
